### PR TITLE
fix(icons): make icon size dependent on font size

### LINKED ISSUE #571: [BUG] Incorrect textfield padding and icons sizes in REM
# 🐞 Bug report

### Description

Text field padding is calculated incorrectly when the main fontSize changes

image (8)

Also the size of the icons is not recalculating

### Reproduction

set fontSize in html other than 16px

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?
icons do not respond to main fontSize 
Снимок экрана от 2021-09-29 11-27-54

Closes #571 

## What is the new behavior?

Снимок экрана от 2021-09-29 11-28-29

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

File: projects/demo/src/assets/process-icons.js [hunk 1]
```diff
@@ -61,11 +61,16 @@ function wrapIcon(source, name) {
 
     const width = parseInt(widthString, 10);
```
Comment (waterplea) [inline projects/demo/src/assets/process-icons.js:62]: There's also `process-icons.ts` which is used by `SvgService` when you define icon on the fly. Same changes need to be applied there.

**Review by waterplea — APPROVED** [review]

**Review by nsbarsukov — APPROVED** [review]
