### PR TITLE
fix(core): fix event propagation on esc

### LINKED ISSUE #622: [BUG] Popup does not close when the input field is filled
# 🐞 Bug report

### Reproduction

* Open some template with  any input field with TuiDialogService
* Type value in text field 
* Press "Esc"

### Actual behavior
* popup doesn't closed
* popup will close only after second press

### Expected behavior
* popup closed on first press

### Versions

-   OS: [Windows/IOS]
-   Browser [Chrome]
-   Angular [10.1.4]
-   Package [2.13.1/2.13.1]

### Additional context
https://user-images.githubusercontent.com/18559077/129353554-7013c267-44d7-4ff7-81c2-5659b0a65893.mp4

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring
-   [ ] Code style update
-   [ ] Build or CI related changes
-   [ ] Documentation content changes

## What is the current behavior?

Closes #622  

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts [hunk 1]
```diff
@@ -139,7 +139,7 @@ export class TuiHostedDropdownComponent implements TuiFocusableElementAccessor {
 
     @HostListener('keydown.esc', ['$event'])
     onKeyDownEsc(event: KeyboardEvent) {
-        if (!this.open) {
+        if (!this.open || !this.content) {
```
Comment (splincode) [inline projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:142]: can we write tests for these cases?

Comment (vladimirpotekhin) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:142]: done :+1:

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
