### PR TITLE
[BUGFIX] update active tab index

### LINKED ISSUE #431: [BUG] TuiTabs with routerLink gets wrong underline on remove
# 🐞 Bug report

### Description

Underline disappears when close previous tab several times.

### Reproduction

Stackblitz: https://stackblitz.com/edit/taiga-starter-pyoyqf

1. Go to https://taiga-starter-pyoyqf.stackblitz.io/?param=4
2. Close tab **Item#0**
3. Underline is ok
4. Close tab **Item#1**
5. Underline is disappeared

Снимок экрана 2021-05-21 в 18 35 54
Снимок экрана 2021-05-21 в 18 36 04

### Expected behavior

Underline corresponds to activated route

### Versions

-   OS: [macOS 10.15.7]
-   Browser [chrome 90.0.4430.212]
-   Angular [12.0.0]
-   Package [@taiga-ui/kit@2.9.1]

### Additional context

Almost the same happens with **tui-tabs-with-more**

### PR DESCRIPTION
**Pull request by ikurilov**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

doesn't update active router link tab index when tabs change

Closes #431 

## What is the new behavior?

update activatedRouterLink active index

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Review by waterplea — APPROVED** [review]

File: projects/kit/components/tabs/tab/tab.providers.ts [hunk 1]
```diff
@@ -31,8 +39,15 @@ export function tabActiveFactory(
     {nativeElement}: ElementRef<HTMLElement>,
     documentRef: Document,
     routerLinkActiveService: Observable<boolean>,
+    mutationObserverService: MutationObserverService,
+    routerLinkActive: RouterLinkActive,
 ): Observable<unknown> {
+    const mutationObserver = routerLinkActive
+        ? mutationObserverService.pipe(filter(() => routerLinkActive.isActive))
```
Comment (MarsiBarsi) [inline projects/kit/components/tabs/tab/tab.providers.ts:46]: don't we need to throttle it to prevent an endless loop in some unpredictable cases? 🤔

**Review by MarsiBarsi — APPROVED** [review]
