### PR TITLE
fix(kit): update native value on day click in input-date-time

### LINKED ISSUE #375: [BUG] InputDateTime selecting date from picker when it's halfway entered
# 🐞 Bug report

If you start typing the date and then decide to pick it from the calendar the textfield does not update to represent the selected date. Other date-related controls should also be checked!

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #375 

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

File: projects/kit/components/input-date-time/input-date-time.component.ts [hunk 1]
```diff
@@ -220,9 +220,16 @@ export class TuiInputDateTimeComponent
 
     onDayClick(day: TuiDay) {
         this.updateValue([day, this.value[1]]);
+        this.updateNativeValue(day);
         this.open = false;
     }
 
+    updateNativeValue(day: TuiDay) {
+        const time = this.nativeValue.split(DATE_TIME_SEPARATOR)[1];
```
Comment (waterplea) [inline projects/kit/components/input-date-time/input-date-time.component.ts:228]: || ''
so you won't need the ternary later

File: projects/kit/components/input-date-time/input-date-time.component.ts [hunk 2]
```diff
@@ -220,9 +220,16 @@ export class TuiInputDateTimeComponent
 
     onDayClick(day: TuiDay) {
         this.updateValue([day, this.value[1]]);
+        this.updateNativeValue(day);
         this.open = false;
     }
 
+    updateNativeValue(day: TuiDay) {
```
Comment (waterplea) [inline projects/kit/components/input-date-time/input-date-time.component.ts:227]: Please make private

**Review by waterplea — APPROVED** [review]
