### PR TITLE
fix(core): `PrimitiveTextfield` fix growing wider than container

### LINKED ISSUE #351: [BUG] TuiInput expanding beyond parent fixed width
# 🐞 Bug report

### Description

The TuiInput component keeps growing in length even though the parent container width is fixed. This happens when the text is longer than the parent container.

image

### Reproduction

https://stackblitz.com/edit/taiga-starter-z98s9q?file=src%2Fapp%2Fapp.component.ts

### Expected behavior

The input should expand at the container width at max and the text inside the input should just scroll.

### Versions

-   OS: Windows 10
-   Browser Chrome v90.0.4430.85
-   Angular 11
-   Package @taiga-ui/kit@2.7.0

### PR DESCRIPTION
**Pull request by waterplea**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #351

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

### CODE REVIEW

File: projects/cdk/utils/miscellaneous/is-element-editable.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+export function isElementEditable(element: HTMLElement): boolean {
+    return (
+        (element instanceof HTMLInputElement && !element.readOnly) ||
+        (element instanceof HTMLTextAreaElement && !element.readOnly) ||
+        element.contentEditable === 'true'
```
Comment (MarsiBarsi) [inline projects/cdk/utils/miscellaneous/is-element-editable.ts:5]: There is also `'plaintext-only'` option. It is actually an editable state...

**Review by MarsiBarsi — APPROVED** [review]
