### PR TITLE
fix(core): dialog not closing due to transparent border, closes #148

### LINKED ISSUE #148: [BUG] Dialog not closing when clicking box shadow
# 🐞 Bug report

### Description

The Dialog will not close when clicking on the box shadow and not the background:

https://user-images.githubusercontent.com/9350951/105728652-aff1ef00-5f2c-11eb-8d5a-eaa01e0b1d44.mp4

### Expected behavior

Dialog should close

### Versions

-   OS: Windows
-   Browser chrome
-   Angular 10
-   Package [e.g. @taiga-ui/cdk@2.0.0]

### PR DESCRIPTION
**Pull request by maartentibau**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

https://user-images.githubusercontent.com/4103756/106378669-e903e680-63a6-11eb-86bc-57f2edffb457.mp4

Closes #148 

## What is the new behavior?

https://user-images.githubusercontent.com/4103756/106378675-f1f4b800-63a6-11eb-8a69-9907bcfaa5e3.mp4

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Comment by waterplea** [comment]
Hello Maarten. This border is there for a reason. It emulates auto margin with minimal value. This way dialog is centered, but there is always some space around it. Like when it's tall and you scroll it to the bottom or top the top. We need to come up with a different solution.

**Comment by maartentibau** [comment]
@waterplea after I submit the PR and was playing around with it a bit more I was thinking the same thing.

I'm gonna try to come up with another solution. Gonna have a look in code to see how the closing mechanism is triggered when you click outside of the dialog.

Update following soon

**Comment by maartentibau** [comment]
@waterplea ... I tried a different approach, it's still WIP ... but how do you like this one?
Am I on the right track?

File: projects/core/components/dialog/dialog.component.ts [hunk 1]
```diff
@@ -71,6 +77,12 @@ export class TuiDialogComponent<O, I> {
             : SMALL_DIALOGS_ANIMATION;
     }
 
+    @HostListener('click', ['$event.target']) hostClick(target: HTMLElement) {
```
Comment (waterplea) [inline projects/core/components/dialog/dialog.component.ts:80]: @MarsiBarsi shouldn't prettier put the method name on a new line?

File: projects/core/components/dialog/dialog.component.ts [hunk 2]
```diff
@@ -71,6 +77,12 @@ export class TuiDialogComponent<O, I> {
...
+        if (target?.classList.contains('ng-trigger')) {
```
Comment (waterplea) [inline projects/core/components/dialog/dialog.component.ts:81]: @maartentibau if you want to check if target for click is the host component, a better way to do it is test `target === currentTarget`. cdk package has a utility function `isCurrentTarget` for this check.

File: projects/core/components/dialog/dialog.component.ts (hunk 1 above)
Comment (MarsiBarsi) [reply projects/core/components/dialog/dialog.component.ts:80]: Unfortunately it shouldn’t. It is just our agreement 😔

File: projects/core/components/dialog/dialog.component.ts (hunk 2 above)
Comment (maartentibau) [reply projects/core/components/dialog/dialog.component.ts:81]: I was a bit confused with the comment, but after a search in the source code I found the `isCurrentTarget` method and understood what you mean... I first thought you were talking about the Angular Material CDK ... but that seemed a bit weird.

File: projects/core/components/dialog/dialog.component.ts (hunk 1 above)
Comment (maartentibau) [reply projects/core/components/dialog/dialog.component.ts:80]: Done

**Comment by maartentibau** [comment]
@waterplea Yes indeed ... that is the approach I took.
Pushed the requested changes.

**Review by waterplea — CHANGES_REQUESTED** [review]
These last examples are broken:
image
Both are broken on small screens (below 600px width) and fullscreen is broken overall. Please take a look at them. Those two modes do not have border radius and do not need that minimal margin, so probably you can tweak CSS a little so your changes are not applied to them or something like that.

**Comment by maartentibau** [comment]
@waterplea sorry.. did not properly test everything my mistake. I think I fixed it all.

File: projects/core/components/dialog/dialog.style.less [hunk 3]
```diff
@@ -2,15 +2,19 @@
 
 :host {
     .text-body-m();
+
+    .dialog-host {
```
Comment (waterplea) [inline projects/core/components/dialog/dialog.style.less:6]: Let's not move it under `:host`, it increases specificity and there's no reason to do so.

File: projects/core/components/dialog/dialog.style.less [hunk 4]
```diff
@@ -52,6 +56,14 @@
         border-radius: 0;
         border: none;
         padding: 48px ~'calc(50vw - 720px / 2)';
+        background: var(--tui-base-01);
+
+        .dialog-host {
+            flex: 1 1 auto;
+            display: inherit;
+            flex-direction: inherit;
```
Comment (waterplea) [inline projects/core/components/dialog/dialog.style.less:64]: Do we need these 3 rules?

File: projects/core/components/dialog/dialog.style.less [hunk 5]
```diff
@@ -52,6 +56,14 @@
         border-radius: 0;
         border: none;
         padding: 48px ~'calc(50vw - 720px / 2)';
```
Comment (waterplea) [inline projects/core/components/dialog/dialog.style.less:58]: How about we move this padding to `.dialog-host`? So that it is the one always responsible for padding.

File: projects/core/components/dialog/dialog.style.less [hunk 6]
```diff
@@ -68,6 +80,12 @@
 
     @media @mobile {
         &[data-size] {
+            .dialog-host {
```
Comment (waterplea) [inline projects/core/components/dialog/dialog.style.less:83]: I think we can move this to its own `@media @mobile` and out of the host for specificity reasons too.

File: projects/core/components/dialog/dialog.style.less (hunk 5 above)
Comment (waterplea) [reply projects/core/components/dialog/dialog.style.less:58]: Also found a bug that between 600 and 720px this causes white paddings around content. This bug is present in current version, might as well fix it here while we're at it :) I think we can move `head` out of that new wrapper you introduced. And we can add border-radius to the wrapper only if it's the first child. Otherwise layout starts to feel a bit tricky.

**Review by waterplea — CHANGES_REQUESTED** [review]
Please look through comments, I think we can improve it a bit with a different layout.

File: projects/core/components/dialog/dialog.style.less (hunk 4 above)
Comment (maartentibau) [reply projects/core/components/dialog/dialog.style.less:64]: Hmm I spend some time yesterday on fixing something and that is why I added those things. It might just be by shuffling some code around that is became useless. Well spotted, thanks!

File: projects/core/components/dialog/dialog.style.less (hunk 6 above)
Comment (maartentibau) [reply projects/core/components/dialog/dialog.style.less:83]: OK .. I hope I put in the correct spot 😋

File: projects/core/components/dialog/dialog.style.less [hunk 7]
```diff
@@ -2,15 +2,19 @@
 
 :host {
     .text-body-m();
+
+    .dialog-host {
+        background: var(--tui-base-01);
+        padding: 32px;
+        background-clip: padding-box;
```
[the remark this answers is not in the document]
Comment (maartentibau) [reply projects/core/components/dialog/dialog.style.less]: Removed

File: projects/core/components/dialog/dialog.style.less (hunk 5 above)
Comment (maartentibau) [reply projects/core/components/dialog/dialog.style.less:57]: https://user-images.githubusercontent.com/4103756/106948734-5f4c7400-672c-11eb-8f2e-79f90647556c.mp4

File: projects/core/components/dialog/dialog.style.less (hunk 3 above)
Comment (maartentibau) [reply projects/core/components/dialog/dialog.style.less:4]: done

File: projects/core/components/dialog/dialog.style.less (hunk 4 above)
Comment (maartentibau) [reply projects/core/components/dialog/dialog.style.less]: Well.. if they are not there you have this

https://user-images.githubusercontent.com/4103756/106953117-4cd53900-6732-11eb-94bc-b75a29b96edc.mp4

File: projects/core/components/dialog/dialog.style.less (hunk 5 above)
Comment (maartentibau) [reply projects/core/components/dialog/dialog.style.less]: Should be fixed

File: projects/core/components/dialog/dialog.style.less (hunk 3 above)
Comment (waterplea) [reply projects/core/components/dialog/dialog.style.less:4]: I mean move it outside of `:host { ... }` :) Otherwise it adds `[ng-host-xxxx]` as a parent to the style which increases the specificity.

Comment (maartentibau) [reply projects/core/components/dialog/dialog.style.less]: done

**Review by waterplea — APPROVED** [review]
