### PR TITLE
fix(kit): fix change detection

### LINKED ISSUE #288: [BUG]  ExpressionChangedAfterItHasBeenCheckedError
# 🐞 Bug report

### Description

There is an error in console, when I click in IputPasswords button show/hide password
```Expression has changed after it was checked. Previous value: 'Скрыть пароль'. Current value: 'Показать пароль'.```
### Reproduction
<tui-root>

  <tui-island size="l" textAlign="center">
    <h2 class="title">Вход в систему</h2>
    <tui-input class="b-form"> Имя пользователя </tui-input>

    <tui-input-password class="tui-space_top-2">
      Введите пароль
    </tui-input-password>

    <button
          tuiButton
          type="button"
          class="tui-island__footer-button"
          appearance="flat"
          (click)="onSubmit()"
          size="l">
          Войти
        </button>
  </tui-island>
</tui-root>

https://stackblitz.com/edit/taiga-starter-yehbav?embed=1&file=src/app/app.component.html

### Expected behavior

Without Error of course :)
### Versions
- OS MacOs Latest
-   Browser [chrome latest]
-   Angular [e.g. 11]
-   Package [e.g. @taiga-ui/cdk latest]

### Additional context
Also I plan Taiga Ui as Main ui-kit in new healthcare project in Russia. I think it can be a united standard of ui in our app's (other 2 projects on Material UI, but it has some problems with customization)

### PR DESCRIPTION
**Pull request by nikitadubinsk**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #288 

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Review by MarsiBarsi — APPROVED** [review]

File: projects/kit/components/input-password/input-password.component.ts [hunk 1]
```diff
@@ -9,6 +9,7 @@ import {
     ViewChild,
 } from '@angular/core';
 import {NgControl} from '@angular/forms';
+
```
Comment (MarsiBarsi) [inline projects/kit/components/input-password/input-password.component.ts:12]: nit: не очень релевантное изменение :)
