### PR TITLE
fix(kit): `Combobox`  open dropdown on cleaner click

### LINKED ISSUE #621: [BUG] The date picker popup does not open after cleaner clicked
# 🐞 Bug report

### Description

The date picker popup does not open after cleaner clicked

### Reproduction

* Open date picker
* select date
* clear date on cleaner

Expected Behavior - Date picker popup opened
Actual Behavior - Date picker popup closed

### Versions

-   OS: [Windows, IOS]
-   Browser [Chrome]
-   Angular [10.1.4]
-   Package [2.13.1/2.13.0]

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring
-   [ ] Code style update
-   [ ] Build or CI related changes
-   [ ] Documentation content changes

Closes #621

## What is the current behavior?

dropdown doesn't open by clicking on the cleaner

## What is the new behavior?

dropdown opens by clicking on the cleaner

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by waterplea** [comment]
I believe the same was also required for `InputDate`, please see of it is needed for other controls with drop-downs.

File: projects/kit/components/input-date-time/input-date-time.component.ts [hunk 1]
```diff
@@ -209,6 +209,7 @@ export class TuiInputDateTimeComponent
     onValueChange(value: string) {
         if (value.length < DATE_FILLER_LENGTH) {
             this.updateValue([null, null]);
+            this.onOpenChange(true);
```
Comment (splincode) [inline projects/kit/components/input-date-time/input-date-time.component.ts:212]: can we test this in unit tests?

**Comment by vladimirpotekhin** [comment]
> I believe the same was also required for `InputDate`, please see of it is needed for other controls with drop-downs.

I made same changes in `InputDateTime`, `InputDate`, `InputDateRange`, `InputMonthRange`, `InputMonth`
Multiselect and InputTime works with cleaner as expected

File: projects/kit/components/input-date-range/input-date-range.component.ts [hunk 2]
```diff
@@ -296,6 +296,7 @@ export class TuiInputDateRangeComponent
 
         if (value.length !== DATE_RANGE_FILLER_LENGTH) {
             this.updateValue(null);
+            this.onOpenChange(true);
```
Comment (waterplea) [inline projects/kit/components/input-date-range/input-date-range.component.ts:299]: This way it would open if we just type date with a keyboard, that's not what we want to happen.

**Review by waterplea — CHANGES_REQUESTED** [review]
Maybe we should just drop `.stop` from cleaner in primitive textfield?

File: projects/kit/components/input-date-range/input-date-range.component.ts (hunk 2 above)
Comment (vladimirpotekhin) [reply projects/kit/components/input-date-range/input-date-range.component.ts:299]: > Maybe we should just drop .stop from cleaner in primitive textfield?
I thought about it, but If open dropdown by click and then click on icon dropdown will close in this case

> This way it would open if we just type date with a keyboard, that's not what we want to happen.
Combobox and multiselect work this way with dropdown, I wanted to do the same. But ok, I got that there is no need here

File: projects/kit/components/combo-box/combo-box.component.ts [hunk 3]
```diff
@@ -224,7 +224,7 @@ export class TuiComboBoxComponent<T>
 
         this.updateValue(this.strict || this.search === '' ? null : this.search);
 
-        if (this.search && this.hostedDropdown) {
+        if (this.hostedDropdown) {
             this.hostedDropdown.updateOpen(true);
```
Comment (waterplea) [inline projects/kit/components/combo-box/combo-box.component.ts:228]: nit: maybe `this.hostedDropdown?.updateOpen(true)`?

**Review by waterplea — APPROVED** [review]
