### PR TITLE
fix(kit): `InputDateTime` fix changing date, `InputTime` open dropdown by click

### LINKED ISSUE #307: [BUG] input time with dropdown only works on arrow keys
# 🐞 Bug report

### Description

input time with dropdown only works on arrow keys, not on input focus or mouse click

### Reproduction

Visit:
https://taiga-ui.dev/components/input-time#dropdown
or
https://stackblitz.com/edit/angular-spfd4l?file=src/app/app.component.ts

Try to open the dropdown with mouse only.

### Expected behavior

Dropdown should open icon click or input focus (maybe configurable)

### Versions

-   OS: Windows
-   Browser: Chrome
-   Angular as per demo

### LINKED ISSUE #317: [BUG] InputDateTime bug
# 🐞 Bug report

### Description

When we choose a date but not choose a time and then we change date from calendar the input does not change the value.

### Reproduction

https://taiga-ui.dev/components/input-date-time
I just pin the link from site.

### Expected behavior

We wanna to use InputDateTime for moments when we don't know the time but know date. Like an universal date input(and time when we need)

### PR DESCRIPTION
**Pull request by waterplea**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #317 
Closes #307 

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

### CODE REVIEW

File: projects/kit/components/input-time/input-time.component.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import {
     ChangeDetectionStrategy,
     ChangeDetectorRef,
     Component,
-    forwardRef,
+    forwardRef, HostListener,
```
Comment (MarsiBarsi) [inline projects/kit/components/input-time/input-time.component.ts:5]: prettier

**Review by MarsiBarsi — CHANGES_REQUESTED** [review]

**Review by MarsiBarsi — APPROVED** [review]
