### PR TITLE
fix(kit): `TuiInputNumber` fix custom formatting

### LINKED ISSUE #888: 🐞 - Input Number Component limiting length when diffrent format is supplied
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

_No response_

### Description

Replication Steps (stackblitz would not allow me to download tiga kit at 2.19.0):  
- On the `tui-input-number` component set decimal to 'never
- Supply a different value for the `TUI_NUMBER_FROMAT` (as seen below) to try and get a normal numeric format where there is a comma after every three numbers until the decimal (ex: 456,444,000.00). 
` {
            provide: TUI_NUMBER_FORMAT,
            useValue: {
                decimalSeparator: '.',
                thousandSeparator: ',',
            },
        },`

Bug: 
This causes the `tui-input-number` component to stop taking in values after 4

Dependencies:
"@taiga-ui/addon-mobile": "^2.19.0",
"@taiga-ui/cdk": "^2.19.0",
"@taiga-ui/core": "^2.19.0",
"@taiga-ui/icons": "^2.19.0",
 "@taiga-ui/kit": "^2.19.0",

"@angular/cli": "12.2.9",

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [x] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring
-   [ ] Code style update
-   [ ] Build or CI related changes
-   [ ] Documentation content changes

## What is the current behavior?

Closes #888  

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Review by nsbarsukov — APPROVED** [review]

File: projects/kit/components/input-number/input-number.component.ts [hunk 1]
```diff
@@ -83,6 +83,7 @@ export class TuiInputNumberComponent
             allowDecimal: decimal !== 'never',
             decimalLimit: precision,
             requireDecimal: decimal === 'always',
+            autoCorrectDecimalSymbol: false,
```
Comment (waterplea) [inline projects/kit/components/input-number/input-number.component.ts:86]: I believe this flag is no longer needed and we can refactor `tuiCreateNuberMask` to simplify it. At least please leave a TODO so we change that in 3.0

**Review by waterplea — APPROVED** [review]
