### PR TITLE
fix(kit): fix icons color in `BadgedContent`

### LINKED ISSUE #719: [BUG] `BadgedContent` with icons
# 🐞 Bug report

### Reproduction
1. Go `BadgedContent`'s API page
2. Set `[contentBottom]` or `[contentTop]` to icon

OR go => https://taiga-ui.dev/components/badged-content/API?tuiMode=null&contentBottom=tuiIconCheck&contentTop=tuiIconCheckCircleLarge&size=xxl

======== ⬇️ ========
BadgedContentBug

### Expected behavior
`BadgedContent` with visible icons.

### Versions

-   @taiga-ui/kit@2.17.0

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #719 

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

File: projects/kit/components/badged-content/badged-content.component.ts [hunk 1]
```diff
@@ -77,6 +77,14 @@ export class TuiBadgedContentComponent {
         return `0 0 0 ${borderWidth}px`;
     }
 
+    get computedColorTop(): string {
+        return this.colorTop || 'var(--tui-success-fill)';
```
Comment (splincode) [inline projects/kit/components/badged-content/badged-content.component.ts:81]: What do you think about move `'var(--tui-success-fill)'`, `'var(--tui-success-fill)'` variables to global options? Then any developers will can override in `forRoot` or `forFeature` these parameters.

Comment (waterplea) [reply projects/kit/components/badged-content/badged-content.component.ts:81]: First of all, we can just move those to default values instead of empty strings. And second, yes, this falls under the task where we move default values to DI tokens.

Comment (vladimirpotekhin) [reply projects/kit/components/badged-content/badged-content.component.ts:81]: No, if I just move those to default value instead of empty string, colored circles will always be displayed.  https://taiga-ui.dev/components/badged-content/API?tuiMode=null&colorBottom=black&colorTop=black 
We need default value only for icons

I propose to move it to TUI_BADGED_CONTENT_OPTIONS  in a separate PR along with `size` and `rounded` as part of this task https://github.com/TinkoffCreditSystems/taiga-ui/issues/133

Comment (splincode) [reply projects/kit/components/badged-content/badged-content.component.ts:81]: I think he mean 

```ts
    @Input()
    @tuiDefaultProp()
    colorTop = 'var(--tui-success-fill)'; // TODO: move to TUI_BADGED_CONTENT_OPTIONS

    // ...
```

Comment (vladimirpotekhin) [reply projects/kit/components/badged-content/badged-content.component.ts:81]: I got it. I mean, there is a getter in component
```    
get bottomNotification(): string {
        return !this.contentBottom && this.colorBottom ? this.colorBottom : '';
}
```
If content is undefined and color is defined we show small circle. So we need to keep empty default colorTop and colorBottom, overwise we will see circles by default

Comment (waterplea) [reply projects/kit/components/badged-content/badged-content.component.ts:81]: I don't think we need a TODO, we will eventually go over all components anyway

**Review by waterplea — APPROVED** [review]

File: projects/kit/components/badged-content/badged-content.component.ts (hunk 1 above)
Comment (vladimirpotekhin) [reply projects/kit/components/badged-content/badged-content.component.ts]: I remade with default value in icon class

**Review by nsbarsukov — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
